services:
  frontend:
    build: .  
    ports:
      - "5000:5000"
    depends_on:
      - backend

  backend:
    image: redis:6.2  # Using the redis image for the backend
    ports:
      - "6379:6379"
  volumes: 
    - redis-data:/data

volumes:
  - redis-data